/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:3a65470e-6190-4b25-b484-9dad5523d55d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_w3xxYf2ci",
    "aws_user_pools_web_client_id": "40jfd345j57fc3c8c37svqhqec",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://524e5az235gfxhgzei3bx2xa6i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gmiizegisnca7msypqziz46hje"
};


export default awsmobile;
